
terraform/backend_config.tf:
	terraform/run-terraform.sh init-backend

terraform_apply: terraform/backend_config.tf ## Apply terraform
	terraform/run-terraform.sh init
	terraform/run-terraform.sh apply

terraform_destroy: terraform/backend_config.tf ## Destroy terraform
	terraform/run-terraform.sh destroy

